name: chatterbox
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  fluttertoast: ^8.2.10
  permission_handler: ^11.3.1
  share_plus: ^10.1.3
  open_file: ^3.5.10
  file_picker: ^8.1.6
  audio_waveforms: ^1.2.0
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  image_path: "assets/logos/chat.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logos/chat.png"

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/


